name: Update RSS Feed

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clona repository
        uses: actions/checkout@v4

      - name: Installa Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Installa dipendenze
        run: |
          pip install requests beautifulsoup4 feedgen

      - name: Esegui script
        run: |
          python generate_feed.py

      - name: Commit feed aggiornato
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git add feed.xml

          git diff --quiet && git diff --staged --quiet || git commit -m "Aggiornamento automatico feed RSS"

          git push
